package proyecto2.logic;
// Generated 19/10/2018 09:29:17 PM by Hibernate Tools 4.3.1

import proyecto2.logic.Bien;
import proyecto2.logic.Labor;




/**
 * Activo generated by hbm2java
 */
public class Activo  implements java.io.Serializable {


     private String codigo;
     private Bien bien;
     private Labor labor;

    public Activo() {
    }

	
    public Activo(String codigo) {
        this.codigo = codigo;
    }
    public Activo(String codigo, Bien bien, Labor labor) {
       this.codigo = codigo;
       this.bien = bien;
       this.labor = labor;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Bien getBien() {
        return this.bien;
    }
    
    public void setBien(Bien bien) {
        this.bien = bien;
    }
    public Labor getLabor() {
        return this.labor;
    }
    
    public void setLabor(Labor labor) {
        this.labor = labor;
    }




}


