package proyecto2.logic;
// Generated 19/10/2018 09:29:17 PM by Hibernate Tools 4.3.1


import proyecto2.logic.Puesto;
import java.util.HashSet;
import java.util.Set;

/**
 * Labor generated by hbm2java
 */
public class Labor  implements java.io.Serializable {


     private Integer idLabor;
     private Dependencia dependencia;
     private Funcionario funcionario;
     private Puesto puesto;
     private Set activos = new HashSet(0);

    public Labor() {
    }

	
    public Labor(Dependencia dependencia, Funcionario funcionario) {
        this.dependencia = dependencia;
        this.funcionario = funcionario;
    }
    public Labor(Dependencia dependencia, Funcionario funcionario, Puesto puesto, Set activos) {
       this.dependencia = dependencia;
       this.funcionario = funcionario;
       this.puesto = puesto;
       this.activos = activos;
    }
   
    public Integer getIdLabor() {
        return this.idLabor;
    }
    
    public void setIdLabor(Integer idLabor) {
        this.idLabor = idLabor;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


