package proyecto2;
// Generated 19/10/2018 09:29:17 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Funcionario funcionario;
     private String username;
     private String password;

    public Usuario() {
    }

	
    public Usuario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Usuario(Funcionario funcionario, String username, String password) {
       this.funcionario = funcionario;
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


