-- MySQL Script generated by MySQL Workbench
-- Thu Oct 18 21:03:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Activos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Activos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Activos` DEFAULT CHARACTER SET utf8 ;
USE `Activos` ;

-- -----------------------------------------------------
-- Table `Activos`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`funcionario` (
  `id` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`dependencia` (
  `codigo` VARCHAR(6) NOT NULL,
  `nombre` VARCHAR(15) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`solicitud` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `cantidad` INT NULL,
  `tipoAdquisicion` VARCHAR(45) NULL,
  `monto` DOUBLE NULL,
  `dependencia` VARCHAR(6) NOT NULL,
  `funcionario` VARCHAR(9) NOT NULL,
  `estado` VARCHAR(25) NULL,
  `comprobante` VARCHAR(10) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Solicitud_dependencia_idx` (`dependencia` ASC),
  INDEX `fk_Solicitud_funcionario1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_Solicitud_dependencia`
    FOREIGN KEY (`dependencia`)
    REFERENCES `Activos`.`dependencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_funcionario1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `Activos`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `consecutivo` INT NULL,
  `tipo` VARCHAR(20) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`bien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`bien` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `modelo` VARCHAR(30) NULL,
  `descripcion` VARCHAR(255) NULL,
  `marca` VARCHAR(30) NULL,
  `precio` DOUBLE NULL,
  `solicitud` INT NOT NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_bien_Solicitud1_idx` (`solicitud` ASC),
  INDEX `fk_bien_categoria1_idx` (`categoria` ASC),
  CONSTRAINT `fk_bien_Solicitud1`
    FOREIGN KEY (`solicitud`)
    REFERENCES `Activos`.`solicitud` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bien_categoria1`
    FOREIGN KEY (`categoria`)
    REFERENCES `Activos`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`puesto` (
  `id_puesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL,
  PRIMARY KEY (`id_puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`labor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`labor` (
  `id_labor` INT NOT NULL AUTO_INCREMENT,
  `puesto` INT NULL,
  `dependencia` VARCHAR(6) NOT NULL,
  `funcionario` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_labor`),
  INDEX `fk_labor_puesto1_idx` (`puesto` ASC),
  INDEX `fk_labor_dependencia1_idx` (`dependencia` ASC),
  INDEX `fk_labor_funcionario1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_labor_puesto1`
    FOREIGN KEY (`puesto`)
    REFERENCES `Activos`.`puesto` (`id_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_labor_dependencia1`
    FOREIGN KEY (`dependencia`)
    REFERENCES `Activos`.`dependencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_labor_funcionario1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `Activos`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(20) NULL,
  `funcionario` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_funcionario1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_usuario_funcionario1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `Activos`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activos`.`activo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activos`.`activo` (
  `codigo` VARCHAR(45) NOT NULL,
  `bien` INT NULL,
  `labor` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_activo_bien1_idx` (`bien` ASC),
  INDEX `fk_activo_labor1_idx` (`labor` ASC),
  CONSTRAINT `fk_activo_bien1`
    FOREIGN KEY (`bien`)
    REFERENCES `Activos`.`bien` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activo_labor1`
    FOREIGN KEY (`labor`)
    REFERENCES `Activos`.`labor` (`id_labor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
