/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.presentation.bien.edicion;

import java.util.Arrays;
import java.util.Observable;
import javax.swing.JOptionPane;
import proyecto2.Application;
import proyecto2.logic.Bien;

/**
 *
 * @author Rodrigo Meléndez
 */
public class BienView extends javax.swing.JDialog implements java.util.Observer {
    BienModel model;
    BienController controller;

    public BienModel getModel() {
        return model;
    }

    public void setModel(BienModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public BienController getController() {
        return controller;
    }

    public void setController(BienController controller) {
        this.controller = controller;
    }
    
    /**
     * Creates new form BienView
     */
    public BienView(/*java.awt.Frame parent, boolean modal*/) {
        //super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Descripcion = new javax.swing.JLabel();
        label_Marca = new javax.swing.JLabel();
        label_Modelo = new javax.swing.JLabel();
        label_Cantidad = new javax.swing.JLabel();
        label_Precio = new javax.swing.JLabel();
        text_Marca = new javax.swing.JTextField();
        text_Modelo = new javax.swing.JTextField();
        text_Cantidad = new javax.swing.JTextField();
        text_Precio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        button_Guardar = new javax.swing.JButton();
        button_Salir = new javax.swing.JButton();
        text_Descripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        label_Descripcion.setText("Descripción");

        label_Marca.setText("Marca");

        label_Modelo.setText("Modelo");

        label_Cantidad.setText("Cantidad");

        label_Precio.setText("Precio");

        text_Cantidad.setText("0");

        text_Precio.setText("0.0");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Bien");

        button_Guardar.setText("Guardar");
        button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_GuardarActionPerformed(evt);
            }
        });

        button_Salir.setText("Salir");
        button_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(label_Precio)
                    .addComponent(label_Cantidad)
                    .addComponent(label_Modelo)
                    .addComponent(label_Marca)
                    .addComponent(label_Descripcion))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button_Guardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_Salir))
                        .addComponent(text_Cantidad)
                        .addComponent(text_Precio)
                        .addComponent(text_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Descripcion)
                    .addComponent(text_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Marca)
                    .addComponent(text_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Modelo)
                    .addComponent(text_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Cantidad)
                    .addComponent(text_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Precio)
                    .addComponent(text_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Guardar)
                    .addComponent(button_Salir))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_GuardarActionPerformed
        if (this.validar()) {
            try {
                this.controller.guardar(this.creaBien());
                JOptionPane.showMessageDialog(this, "Datos registrados", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_button_GuardarActionPerformed

    private void button_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button_SalirActionPerformed
    
    public boolean validar() { //Retorna false si no hay errores
        boolean error = true;
        this.label_Descripcion.setForeground(Application.COLOR_OK);
        this.label_Marca.setForeground(Application.COLOR_OK);
        this.label_Modelo.setForeground(Application.COLOR_OK);
        this.label_Cantidad.setForeground(Application.COLOR_OK);
        this.label_Precio.setForeground(Application.COLOR_OK);
        if (this.text_Descripcion.getText().isEmpty()) {
            this.label_Descripcion.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (this.text_Marca.getText().isEmpty()) {
            this.label_Marca.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (this.text_Modelo.getText().isEmpty()) {
            this.label_Modelo.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (Integer.parseInt(this.text_Cantidad.getText()) == 0) {
            this.label_Cantidad.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        if (Double.parseDouble(this.text_Precio.getText()) == 0.0) {
            this.label_Precio.setForeground(Application.COLOR_ERROR);
            error = false;
        }
        return error;
    }
    
    public Bien creaBien() {
        Bien bien = new Bien();
        bien.setDescripcion(text_Descripcion.getText());
        bien.setMarca(text_Marca.getText());
        bien.setModelo(text_Modelo.getText());
        bien.setCantidad(Integer.parseInt(text_Cantidad.getText()));
        bien.setPrecio(Double.parseDouble(text_Precio.getText()));
        return bien;
    }
    
    public void limpiarErrores() {
        this.label_Descripcion.setForeground(Application.COLOR_OK);
        this.label_Marca.setForeground(Application.COLOR_OK);
        this.label_Modelo.setForeground(Application.COLOR_OK);
        this.label_Cantidad.setForeground(Application.COLOR_OK);
        this.label_Precio.setForeground(Application.COLOR_OK);
    }
    
    public void fromBien(Bien actual){
        this.text_Descripcion.setEnabled(model.getModo() == Application.MODO_AGREGAR);
        this.text_Descripcion.setText(actual.getDescripcion());
        Boolean editable = Arrays.asList(Application.MODO_AGREGAR, Application.MODO_EDITAR).contains(model.getModo());
        
        this.text_Marca.setEnabled(editable);
        this.text_Marca.setText(actual.getMarca());
        
        this.text_Modelo.setEnabled(editable);
        this.text_Modelo.setText(actual.getModelo());
        
        this.text_Cantidad.setEnabled(editable);
        this.text_Cantidad.setText(String.valueOf(actual.getCantidad()));
        
        this.text_Precio.setEnabled(editable);
        this.text_Precio.setText(String.valueOf(actual.getPrecio()));
        
        this.button_Guardar.setVisible(editable);
        this.validate();
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Guardar;
    private javax.swing.JButton button_Salir;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_Cantidad;
    private javax.swing.JLabel label_Descripcion;
    private javax.swing.JLabel label_Marca;
    private javax.swing.JLabel label_Modelo;
    private javax.swing.JLabel label_Precio;
    private javax.swing.JTextField text_Cantidad;
    private javax.swing.JTextField text_Descripcion;
    private javax.swing.JTextField text_Marca;
    private javax.swing.JTextField text_Modelo;
    private javax.swing.JTextField text_Precio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.limpiarErrores();
        Bien actual = model.getCurrent();
        this.fromBien(actual);
    }
}
